// app.vue
<script setup lang="ts">
useSeoMeta({
  title: 'CP Dashboard',
  ogTitle: 'CP Dashboard',
  description: '必要な情報を一目で確認できる、タイマー付きのダッシュボードサイト。',
  ogDescription: '必要な情報を一目で確認できる、タイマー付きのダッシュボードサイト。',
  ogImage: 'https://coreinion.github.io/cp-dashboard/ogp.png',
  twitterCard: 'summary_large_image',
});

useHead({
  htmlAttrs: {
    lang: 'ja',
  },
  link: [
    {
      rel: 'icon',
      type: 'image/x-icon',
      href: 'favicon.ico',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      href: 'icon.svg',
    },
    {
      rel: 'apple-touch-icon',
      href: 'pwa/apple-touch-icon-180x180.png',
    },
  ],
});

const widthState = widthScreenSize();

// 一回でも画面がクリックされたかどうか
const firstClick = useState(() => false);

defaultAlertAudioSource().value = `${useRuntimeConfig().app.baseURL}alert.mp3`;

onMounted(async () => {
  // 画面がクリックされたらfirstClickをtrueにする
  document.body.onclick = () => {
    firstClick.value = true;
  };

  // ウィンドウサイズを取得
  widthState.value = window.innerWidth;

  // 画面サイズ更新時にstateを更新するようにする
  window.addEventListener('resize', () => {
    widthState.value = window.innerWidth;
  });

  try {
    // スリープを無効化
    await navigator.wakeLock.request('screen');
    // タブ切り替え後でも持続するようにする
    document.addEventListener('visibilitychange', async () => {
      if (document.visibilityState === 'visible') {
        await navigator.wakeLock.request('screen');
      }
    });
  } catch (e) {
    console.warn(e);
  }

  // OPFSからチャイム音源とアラート音源を読み込む
  const opfsRoot = await navigator.storage.getDirectory();

  // チャイム音源を読み込む
  try {
    const chimeHandle = await opfsRoot.getFileHandle('chime.mp3', { create: false });
    const chimeBuffer = await chimeHandle.getFile();
    chimeSource().value = URL.createObjectURL(chimeBuffer);
  } catch (e) {
    console.warn(e);
  }

  // 予鈴音源を読み込む
  try {
    const preChimeHandle = await opfsRoot.getFileHandle('pre-chime.mp3', { create: false });
    const preChimeBuffer = await preChimeHandle.getFile();
    preChimeSource().value = URL.createObjectURL(preChimeBuffer);
  } catch (e) {
    console.warn(e);
  }

  // アラート音源を読み込む
  try {
    const alertHandle = await opfsRoot.getFileHandle('alert.mp3', { create: false });
    const alertBuffer = await alertHandle.getFile();
    timerAlertSource().value = URL.createObjectURL(alertBuffer);
  } catch (e) {
    console.warn(e);
  }

  // @ts-ignore
  await import("pure-snow.js").then(({ createSnow, showSnow }) => {
    createSnow();
    showSnow(isSnowEnabled().value);
  });
});
</script>

<template>
  <div id="snow"></div>
  <NuxtPwaManifest />
  <NuxtLayout>
    <div v-if="!firstClick" class="toast toast-top toast-center">
      <div class="alert alert-warning">
        <span>
          <IconCSS class="icon" name="uil:exclamation-triangle" size="2vw" />
          アラームを動作させるために、画面を一回以上クリックしてください！
        </span>
      </div>
    </div>

    <!-- 大画面デバイスの表示 -->
    <div v-if="widthState >= 1280" class="min-h-screen flex flex-row text-center gap-2">
      <div class="basis-[20.0%] flex flex-row justify-between">
        <status></status>
      </div>

      <div class="grow">
        <clock></clock>
      </div>

      <div class="basis-[15.0%] flex flex-col items-end m-3 gap-4">
        <report></report>
        <div class="grow m-2 flex flex-col justify-end gap-2">
          <TimerSetting></TimerSetting>
          <span>Copyright © 2024 CoreNion</span>
          <a href="https://github.com/CoreNion/cp-dashboard/" class="link">Source Code / Licence</a>
        </div>
      </div>
    </div>

    <!-- 小画面デバイスの表示　-->
    <div v-if="widthState <= 1280" class="min-h-screen min-w-full flex flex-col items-center text-center">
      <clock class="grow"></clock>
      <TimerSetting class="m-2"></TimerSetting>
      <div class="flex flex-row gap-5">
        <span>Copyright © 2024 CoreNion</span>
        <a href="https://github.com/CoreNion/cp-dashboard/" class="link">Source Code / Licence</a>
      </div>
    </div>
  </NuxtLayout>
</template>

// next/app/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useWindowSize } from '../hooks/useWindowSize';

export default function Home() {
  const { width } = useWindowSize();
  const [firstClick, setFirstClick] = useState(false);

  useEffect(() => {
    const handleClick = async () => {
      if (!firstClick) {
        try {
          const wakeLock = await navigator.wakeLock.request('screen');
          document.addEventListener('visibilitychange', async () => {
            if (document.visibilityState === 'visible') {
              await navigator.wakeLock.request('screen');
            }
          });
        } catch (e) {
          console.warn(e);
        }

        new Audio("/beep.mp3").play().catch(e => console.warn(e));

        setFirstClick(true);
      }
    };

    document.body.addEventListener('click', handleClick);

    return () => {
      document.body.removeEventListener('click', handleClick);
    };
  }, [firstClick]);

  return (
    <>
      {!firstClick && (
        <div className="toast toast-top toast-center whitespace-normal z-50 w-full">
          <div className="alert alert-warning">
            <p>
              <span>チャイムやタイマーを正常に動作させるため、1回は画面をクリックしてください。</span>
              <br />
              <span>画面をクリックした後、バックグラウンドで正常に動作させるために、短い効果音が1回再生されます。</span>
            </p>
          </div>
        </div>
      )}

      {width >= 1280 ? (
        <div className="min-h-[100dvh] flex flex-row text-center gap-2">
          <div className="basis-[20.0%] flex flex-row justify-between">
            {/* Status Component */}
            <div className="w-full h-full bg-gray-200">Status</div>
          </div>

          <div className="grow m-auto">
            {/* Clock Component */}
            <div className="w-full h-full bg-gray-300">Clock</div>
          </div>

          <div className="basis-[15.0%] flex flex-col items-end m-3 gap-4">
            {/* Report Component */}
            <div className="w-full h-48 bg-gray-200">Report</div>
            <div className="grow m-2 flex flex-col justify-end gap-2">
              <button className="btn btn-neutral" onClick={() => window.location.reload()}>再読み込み</button>
              {/* TimerSetting Component */}
              <div className="w-full h-12 bg-gray-200">TimerSetting</div>
              <span>Copyright © 2024 CoreNion</span>
            </div>
          </div>
        </div>
      ) : (
        <div className="min-h-[100dvh] min-w-full flex flex-col text-center mb-2">
          <div className="navbar bg-neutral">
            <div className="navbar-start">
              <button className="btn" onClick={() => window.location.reload()}>
                {/* Redo Icon */}
              </button>
            </div>
            <div className="navbar-center">
              <a className="btn btn-ghost text-xl text-neutral-content">Campus Dashboard</a>
            </div>
            <div className="navbar-end">
              {/* Settings Component */}
              <div className="w-12 h-12 bg-gray-200">Settings</div>
            </div>
          </div>
          <div className="grow m-auto">
            {/* Clock Component */}
            <div className="w-full h-full bg-gray-300">Clock</div>
          </div>
          {/* TimerSetting Component */}
          <div className="w-full h-12 bg-gray-200">TimerSetting</div>
          <div className="flex flex-row justify-center gap-5 my-3">
            <span>Copyright © 2024 CoreNion</span>
            <a href="https://github.com/CoreNion/cp-dashboard/" className="link">Source Code / Licence</a>
          </div>
        </div>
      )}
    </>
  );
}
