// components/modals/settings.vue
<script setup lang="ts">
// チャイムの音源
const chimeSourceState = chimeSource();
// チャイムのファイル名
const chimeFileNameState = chimeFileName();
// 予鈴の音源
const preChimeSourceState = preChimeSource();
// 予鈴のファイル名
const preChimeFileNameState = preChimeFileName();
// タイマーのアラート音源
const timerAlertSourceState = timerAlertSource();
// タイマーのファイル名
const alertFileNameState = alertFileName();

// チャイムの鳴動状態
const isChimeEnabledState = isChimeEnabled();
// 予鈴の鳴動状態
const isPreChimeEnabledState = isPreChimeEnabled();

// 音源変更時の処理
const onAudioChange = async (e: Event, fileName: string, sourceState: globalThis.Ref<HTMLAudioElement>, fileNameState: globalThis.Ref<string>) => {
  // ファイルを読み込む
  if (!(e.target instanceof HTMLInputElement)) return;
  const file = e.target.files?.[0];
  if (!file) return;

  // OPFSにファイルを保存
  saveFile(file, fileName);
  // メモリ上の音源を更新
  sourceState.value = new Audio(URL.createObjectURL(file));
  sourceState.value.load();
  // ファイル名を更新
  fileNameState.value = file.name;
}

// 音源削除時の処理
const removeAudio = (sourceState: globalThis.Ref<HTMLAudioElement>, fileNameState: globalThis.Ref<string>, origFileName: String) => {
  // OPFSからファイルを削除
  removeFile(fileNameState.value);

  // 音源/名前を元に戻す
  fileNameState.value = 'デフォルトの音声';
  sourceState.value = new Audio(`${useRuntimeConfig().app.baseURL}/${origFileName}`);
  sourceState.value.load();
}

const onAlertAudioChange = async (e: Event) => {
  onAudioChange(e, 'alert.mp3', timerAlertSourceState, alertFileNameState);
}

const removeAlertAudio = () => {
  removeAudio(timerAlertSourceState, alertFileNameState, "alert.mp3");
}

const onChimeAudioChange = async (e: Event) => {
  onAudioChange(e, 'chime.mp3', chimeSourceState, chimeFileNameState);
}

const removeChimeAudio = () => {
  removeAudio(chimeSourceState, chimeFileNameState, "chime.mp3");
}

const onPreChimeAudioChange = async (e: Event) => {
  onAudioChange(e, 'pre-chime.mp3', preChimeSourceState, preChimeFileNameState);
}

const removePreChimeAudio = () => {
  removeAudio(preChimeSourceState, preChimeFileNameState, "pre-chime.mp3");
}

// 音源を再生
const playAudio = (audio: HTMLAudioElement) => {
  audio.volume = 1.0;
  audio.play();
}
</script>

<template>
  <div>
    <h3 class="font-bold text-lg">設定</h3>
    <p class="pt-2">
      <GeneralSetting></GeneralSetting>
      <DynamicModal btnTitle="天気設定" :btn-wfull="true">
        <WeatherSetting></WeatherSetting>
      </DynamicModal>

      <div class="mt-3">
        <DynamicModal linkTypeButton btnTitle="センサーの記録" class="mt-3">
          <SensorRecord></SensorRecord>
        </DynamicModal>
      </div>
    </p>

    <div class="divider"></div>

    <h4 class="font-bold">音声設定</h4>
    <p class="py-3">
      <AudioSetting labelText="タイマー終了時" :fileName="alertFileNameState" :source="timerAlertSourceState"
        :onAudioChange="onAlertAudioChange" :removeAudio="removeAlertAudio" :playAudio="playAudio" />

      <AudioSetting labelText="チャイム" :fileName="chimeFileNameState" :source="chimeSourceState"
        :onAudioChange="onChimeAudioChange" :removeAudio="removeChimeAudio" :playAudio="playAudio" />

      <AudioSetting labelText="予鈴チャイム" :fileName="preChimeFileNameState" :source="preChimeSourceState"
        :onAudioChange="onPreChimeAudioChange" :removeAudio="removePreChimeAudio" :playAudio="playAudio" />

      <label class="label cursor-pointer mt-4">
        <span class="label-text">チャイム鳴動状態</span>
        <input type="checkbox" class="toggle toggle-secondary" v-model="isChimeEnabledState" />
      </label>
      <label class="label cursor-pointer mt-4">
        <span class="label-text">予鈴鳴動状態</span>
        <input type="checkbox" class="toggle toggle-secondary" v-model="isPreChimeEnabledState" />
      </label>
    </p>
    <DynamicModal btnTitle="チャイム設定" :btn-wfull="true">
      <ChimeSetting></ChimeSetting>
    </DynamicModal>

    <div class="divider"></div>

    <h4 class="font-bold">宣伝機能設定 (大画面のみ)</h4>
    <AdSetting></AdSetting>
    <DynamicModal :btn-wfull="true" btnTitle="カウントダウン設定">
      <CountdownSetting></CountdownSetting>
    </DynamicModal>

    <div class="divider"></div>

    <span class="font-light">First Built by CoreNion (N6)</span>
    <br>
    <span class="font-light">Special Thanks to Shibuya CP🫶</span>
    <div class="flex flex-row justify-around mt-3">
      <a href="https://github.com/CoreNion/cp-dashboard/wiki/" class="link">ドキュメント</a>
      <a href="https://github.com/CoreNion/cp-dashboard/" class="link">Source Code</a>
    </div>
  </div>
</template>

// next/components/modals/Settings.tsx
'use client';

import { useState, useCallback } from 'react';

// TODO: これらのカスタムフックとユーティリティ関数は後で実装する
const useChimeSource = () => useState<HTMLAudioElement | null>(null);
const useChimeFileName = () => useState('デフォルトの音声');
const usePreChimeSource = () => useState<HTMLAudioElement | null>(null);
const usePreChimeFileName = () => useState('デフォルトの音声');
const useTimerAlertSource = () => useState<HTMLAudioElement | null>(null);
const useAlertFileName = () => useState('デフォルトの音声');
const useIsChimeEnabled = () => useState(true);
const useIsPreChimeEnabled = () => useState(true);

// 仮のファイル操作関数
const saveFile = (file: File, fileName: string) => {
  console.log(`Saving file: ${fileName}`);
  // 実際にはIndexedDBやサーバーに保存するロジック
};
const removeFile = (fileName: string) => {
  console.log(`Removing file: ${fileName}`);
  // 実際にはIndexedDBやサーバーから削除するロジック
};

// TODO: サブコンポーネントは後で移行する
const GeneralSetting = () => <div className="w-full h-full bg-gray-200">GeneralSetting</div>;
const WeatherSetting = () => <div className="w-full h-full bg-gray-200">WeatherSetting</div>;
const SensorRecord = () => <div className="w-full h-full bg-gray-200">SensorRecord</div>;
const ChimeSetting = () => <div className="w-full h-full bg-gray-200">ChimeSetting</div>;
const AdSetting = () => <div className="w-full h-full bg-gray-200">AdSetting</div>;
const CountdownSetting = () => <div className="w-full h-full bg-gray-200">CountdownSetting</div>;

// DynamicModal コンポーネントの仮実装
export const DynamicModal = ({ children, btnTitle, btnWfull, linkTypeButton }: {
  children: React.ReactNode;
  btnTitle: string;
  btnWfull?: boolean;
  linkTypeButton?: boolean;
}) => {
  const buttonClass = `btn ${btnWfull ? 'w-full' : ''} ${linkTypeButton ? 'btn-link' : 'btn-neutral'}`;
  return (
    <button className={buttonClass} onClick={() => console.log(`${btnTitle} clicked`)}>
      {btnTitle}
    </button>
  );
};

interface AudioSettingProps {
  labelText: string;
  fileName: string;
  source: HTMLAudioElement | null;
  onAudioChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  removeAudio: () => void;
  playAudio: (audio: HTMLAudioElement) => void;
}

const AudioSetting: React.FC<AudioSettingProps> = ({ labelText, fileName, source, onAudioChange, removeAudio, playAudio }) => (
  <div className="py-3">
    <label className="label">
      <span className="label-text">{labelText}</span>
    </label>
    <div className="flex flex-row items-center gap-2">
      <input type="file" accept="audio/*" className="file-input file-input-bordered w-full max-w-xs" onChange={onAudioChange} />
      <button className="btn btn-sm btn-outline" onClick={() => source && playAudio(source)} disabled={!source}>再生</button>
      <button className="btn btn-sm btn-outline btn-error" onClick={removeAudio}>削除</button>
    </div>
    <p className="text-sm text-gray-500 mt-1">現在のファイル: {fileName}</p>
  </div>
);

export default function Settings() {
  const [chimeSourceState, setChimeSourceState] = useChimeSource();
  const [chimeFileNameState, setChimeFileNameState] = useChimeFileName();
  const [preChimeSourceState, setPreChimeSourceState] = usePreChimeSource();
  const [preChimeFileNameState, setPreChimeFileNameState] = usePreChimeFileName();
  const [timerAlertSourceState, setTimerAlertSourceState] = useTimerAlertSource();
  const [alertFileNameState, setAlertFileNameState] = useAlertFileName();
  const [isChimeEnabledState, setIsChimeEnabledState] = useIsChimeEnabled();
  const [isPreChimeEnabledState, setIsPreChimeEnabledState] = useIsPreChimeEnabled();

  const onAudioChange = useCallback(async (e: React.ChangeEvent<HTMLInputElement>, fileName: string, sourceSetter: React.Dispatch<React.SetStateAction<HTMLAudioElement | null>>, fileNameSetter: React.Dispatch<React.SetStateAction<string>>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    saveFile(file, fileName);
    const audio = new Audio(URL.createObjectURL(file));
    audio.load();
    sourceSetter(audio);
    fileNameSetter(file.name);
  }, []);

  const removeAudio = useCallback((sourceSetter: React.Dispatch<React.SetStateAction<HTMLAudioElement | null>>, fileNameSetter: React.Dispatch<React.SetStateAction<string>>, origFileName: string) => {
    removeFile(fileNameSetter[0]); // fileNameSetterはuseStateのsetterなので、[0]で現在の値を取得
    fileNameSetter('デフォルトの音声');
    const audio = new Audio(`/${origFileName}`); // publicディレクトリからのパス
    audio.load();
    sourceSetter(audio);
  }, []);

  const playAudio = useCallback((audio: HTMLAudioElement) => {
    audio.volume = 1.0;
    audio.play().catch(e => console.warn("Audio play failed:", e));
  }, []);

  const onAlertAudioChange = (e: React.ChangeEvent<HTMLInputElement>) => onAudioChange(e, 'alert.mp3', setTimerAlertSourceState, setAlertFileNameState);
  const removeAlertAudio = () => removeAudio(setTimerAlertSourceState, setAlertFileNameState, "alert.mp3");

  const onChimeAudioChange = (e: React.ChangeEvent<HTMLInputElement>) => onAudioChange(e, 'chime.mp3', setChimeSourceState, setChimeFileNameState);
  const removeChimeAudio = () => removeAudio(setChimeSourceState, setChimeFileNameState, "chime.mp3");

  const onPreChimeAudioChange = (e: React.ChangeEvent<HTMLInputElement>) => onAudioChange(e, 'pre-chime.mp3', setPreChimeSourceState, setPreChimeFileNameState);
  const removePreChimeAudio = () => removeAudio(setPreChimeSourceState, setPreChimeFileNameState, "pre-chime.mp3");

  return (
    <div>
      <h3 className="font-bold text-lg">設定</h3>
      <p className="pt-2">
        <GeneralSetting />
        <DynamicModal btnTitle="天気設定" btnWfull={true}>
          <WeatherSetting />
        </DynamicModal>

        <div className="mt-3">
          <DynamicModal linkTypeButton btnTitle="センサーの記録">
            <SensorRecord />
          </DynamicModal>
        </div>
      </p>

      <div className="divider"></div>

      <h4 className="font-bold">音声設定</h4>
      <p className="py-3">
        <AudioSetting
          labelText="タイマー終了時"
          fileName={alertFileNameState}
          source={timerAlertSourceState}
          onAudioChange={onAlertAudioChange}
          removeAudio={removeAlertAudio}
          playAudio={playAudio}
        />

        <AudioSetting
          labelText="チャイム"
          fileName={chimeFileNameState}
          source={chimeSourceState}
          onAudioChange={onChimeAudioChange}
          removeAudio={removeChimeAudio}
          playAudio={playAudio}
        />

        <AudioSetting
          labelText="予鈴チャイム"
          fileName={preChimeFileNameState}
          source={preChimeSourceState}
          onAudioChange={onPreChimeAudioChange}
          removeAudio={removePreChimeAudio}
          playAudio={playAudio}
        />

        <label className="label cursor-pointer mt-4">
          <span className="label-text">チャイム鳴動状態</span>
          <input type="checkbox" className="toggle toggle-secondary" checked={isChimeEnabledState} onChange={() => setIsChimeEnabledState(!isChimeEnabledState)} />
        </label>
        <label className="label cursor-pointer mt-4">
          <span className="label-text">予鈴鳴動状態</span>
          <input type="checkbox" className="toggle toggle-secondary" checked={isPreChimeEnabledState} onChange={() => setIsPreChimeEnabledState(!isPreChimeEnabledState)} />
        </label>
      </p>
      <DynamicModal btnTitle="チャイム設定" btnWfull={true}>
        <ChimeSetting />
      </DynamicModal>

      <div className="divider"></div>

      <h4 className="font-bold">宣伝機能設定 (大画面のみ)</h4>
      <AdSetting />
      <DynamicModal btnWfull={true} btnTitle="カウントダウン設定">
        <CountdownSetting />
      </DynamicModal>

      <div className="divider"></div>

      <span className="font-light">First Built by CoreNion (N6)</span>
      <br />
      <span className="font-light">Special Thanks to Shibuya CP🫶</span>
      <div className="flex flex-row justify-around mt-3">
        <a href="https://github.com/CoreNion/cp-dashboard/wiki/" className="link">ドキュメント</a>
        <a href="https://github.com/CoreNion/cp-dashboard/" className="link">Source Code</a>
      </div>
    </div>
  );
}
